// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package blogs

import (
	"database/sql"
)

type Blog struct {
	ID         int64
	Title      sql.NullString
	Content    sql.NullString
	CreatedAt  sql.NullTime
	ModifiedAt sql.NullTime
}
